CREATE TABLE IF NOT EXISTS policy (
  policy_id BIGINT PRIMARY KEY,
  effective_date DATE,
  owner_id BIGINT,
  owner_name VARCHAR(100),
  owner_birth_date DATE,
  insured_id BIGINT,
  insured_name VARCHAR(100),
  insured_birth_date DATE,
  current_status VARCHAR(50),
  product_name VARCHAR(100),
  billing_type VARCHAR(50),
  issue_date DATE,
  paid_to_date DATE,
  overloan_expiry_date DATE,
  amount_billed BIGINT,
  suffix INT,
  premium_mode VARCHAR(20),
  sundry_amount BIGINT,
  true_premium BIGINT,
  last_mode_premium BIGINT,
  currency VARCHAR(20),
  overloan_least_amount BIGINT,
  full_apa_least_amount BIGINT
);
