CREATE TABLE IF NOT EXISTS policy (
  policy_id BIGINT PRIMARY KEY,
  eff_date DATE,
  owner_id BIGINT,
  owner_name VARCHAR(100),
  owner_birth DATE,
  insured_id BIGINT,
  insured_name VARCHAR(100),
  insured_birth DATE,
  status VARCHAR(50),
  product VARCHAR(100),
  billing VARCHAR(50),
  issue_date DATE,
  paid_to DATE,
  overloan_exp DATE,
  amt_billed BIGINT,
  suffix INT,
  prem_mode VARCHAR(20),
  sundry_amt BIGINT,
  true_prem BIGINT,
  last_prem BIGINT,
  curr VARCHAR(20),
  overloan_least BIGINT,
  apa_least BIGINT
);
